version: "3"

services:
  server:
    build:
      context: server
      args:
        CACHE_VERSION: ${CACHE_VERSION-2017.1}
    ports:
      - "${CACHE_WEBPORT-57772}:57772"
      - "${CACHE_PORT-1972}:1972"
    volumes:
      - ~/cache.key:/usr/cachesys/mgr/cache.key
      - ./server/src:/opt/blocks/src
  web:
    build:
      context: web
    links:
      - server
    environment:
      - DB_HOST=server
      - DB_PORT=${CACHE_WEBPORT-57772}
      - WEB_PORT=${WEB_PORT-80}
    ports:
      - "${WEB_PORT-80}:${WEB_PORT-80}"
    volumes:
      - node_modules:/opt/app/node_modules
      - web_build:/opt/app/build
      - ./web:/opt/app
volumes:
  node_modules: null
  web_build: null
