version: "3"

services:
  server:
    build:
      context: server
      dockerfile: Dockerfile.iris
      args:
        IRIS_VERSION: ${IRIS_VERSION-2018.1}
    ports:
      - "${IRIS_WEBPORT-52773}:52773"
      - "${IRIS_PORT-51773}:51773"
    volumes:
      - ~/iris.key:/usr/irissys/mgr/iris.key
      - ./server/src:/opt/blocks/src
  web:
    build:
      context: web
    links:
      - server
    environment:
      - DB_HOST=server
      - DB_PORT=${IRIS_WEBPORT-52773}
      - WEB_PORT=${WEB_PORT-80}
    ports:
      - "${WEB_PORT-80}:${WEB_PORT-80}"
    volumes:
      - node_modules:/opt/app/node_modules
      - web_build:/opt/app/build
      - ./web:/opt/app
volumes:
  node_modules: null
  web_build: null
