version: "3"

services:
  cache:
    build:
      context: cache
      args:
        CACHE_KEY: ${CACHE_KEY}
        CACHE_VERSION: ${CACHE_VERSION}
    ports:
      - "${CACHE_WEBPORT-57772}:57772"
      - "${CACHE_PORT-1972}:1972"
    volumes:
      - ./cache/src:/opt/blocks/src
      - blocks_data:/opt/blocks
  web:
    build:
      context: web
    links:
      - cache:db
    environment:
      - DB_HOST=db
      - DB_PORT=${CACHE_WEBPORT-57772}
      - WEB_PORT=${WEB_PORT-80}
    ports:
      - "${WEB_PORT-80}:${WEB_PORT-80}"
    volumes:
      - node_modules:/opt/app/node_modules
      - web_build:/opt/app/build
      - ./web:/opt/app
volumes:
  node_modules: null
  web_build: null
  blocks_data: null
