version: "2.4"

services:
  server:
    extends:
      file: docker-compose.${MODE:-iris}.yml
      service: server
    volumes:
      - ./out:/opt/blocks/out
  web:
    extends:
      file: docker-compose.${MODE:-iris}.yml
      service: web
    build:
      context: web
    links:
      - server
    environment:
      - DB_HOST=server
      - WEB_PORT=${WEB_PORT-80}
    ports:
      - "${WEB_PORT-80}:${WEB_PORT-80}"
    volumes:
      - node_modules:/opt/app/node_modules
      - web_build:/opt/app/build
      - ./web:/opt/app
volumes:
  node_modules: null
  web_build: null
