version: "2.4"

services:
  server:
    build:
      context: server
      dockerfile: Dockerfile.iris
    command: --check-caps false
    ports:
      - 1972
      - 52773
    volumes:
#      - ~/iris.key:/usr/irissys/mgr/iris.key
      - ./server/src:/opt/blocks/src
  web:
    environment:
      - DB_PORT=52773
