version: "2.4"

services:
  server:
    build:
      context: server
      dockerfile: Dockerfile.iris
      args:
        IRIS_VERSION: ${IRIS_VERSION:-2020.1.0.209.0}
    ports:
      - 52773
      - 51773
    volumes:
      - ~/iris.key:/usr/irissys/mgr/iris.key
      - ./server/src:/opt/blocks/src
  web:
    environment:
      - DB_PORT=52773
