version: "2.4"

services:
  server:
    build:
      context: server
      dockerfile: Dockerfile.iris
    ports:
      - "${IRIS_WEBPORT-52773}:52773"
      - "${IRIS_PORT-51773}:51773"
    volumes:
      - ~/iris.key:/usr/irissys/mgr/iris.key
      - ./server/src:/opt/blocks/src
  web:
    environment:
      - DB_PORT=52773
