name: zpm
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '10.x'
      - run: cd web && npm ci
      - run: cd web && npm run build:prod
      - name: zpm
        uses: isc-zpm/actions@master
